<?php

use app\models\grammar\exercise\Exercise;
use MongoDB\BSON\ObjectId;
use yii\mongodb\Migration;

class m200709_074153_fill_100_present_simple_exercise_collection extends Migration
{
    private array $_sentences = [
        'Я помню это.',
        'Я понимаю тебя.',
        'Я так думаю.',
        'Мы говорим по-английски.',
        'Я знаю это очень хорошо.',
        'Ты мне помогаешь.',
        'Я живу в России.',
        'Я очень хорошо понимаю тебя.',
        'Я живу в этом городе.',
        'Мы помним это.',
        'Я говорю по-английски.',
        'Я там работаю.',
        'Они мне помогают.',
        'Мы тебя понимаем.',
        'У меня есть идея.',
        'У меня есть брат.',
        'Они ходят в школу.',
        'Вы очень хорошо говорите по-английски.',
        'У меня есть машина.',
        'Мы здесь живем.',
        'Я очень хорошо помню это.',
        'Я хожу на работу.',
        'Я здесь учусь.',
        'Я это хочу.',
        'Мы так думаем.',
        'Я там учусь.',
        'Я это знаю.',
        'Я здесь работаю.',
        'Они ходят на работу.',
        'Ты это знаешь.',
        'Я работаю.',
        'Я живу в этой стране.',
        'Мы живем в России.',
        'У меня есть сестра.',
        'Ты это видишь.',
        'Я хожу в школу.',
        'Я понимаю.',
        'Мы живем в этой стране.',
        'Я это вижу.',
        'Это выглядит странно.',
        'Он читает по-английски.',
        'Она помнит это.',
        'Это выглядит интересно.',
        'Он работает очень усердно.',
        'Ты работаешь очень усердно.',
        'Он мне помогает.',
        'Он очень хорошо понимает тебя.',
        'Он также работает здесь.',
        'Это действительно происходит.',
        'Она работает очень усердно.',
        'Она чувствует себя счастливой.',
        'Он также это помнит.',
        'Он живет в этом доме.',
        'Она тоже там работает.',
        'Он это знает.',
        'Она действительно это помнит.',
        'Она тоже так думает.',
        'Он тоже это знает.',
        'Она живет в том месте.',
        'Она любит тебя.',
        'Она говорит по-английски очень хорошо.',
        'Он так думает.',
        'Он живет в этой стране.',
        'Она читатет английские книги.',
        'Я люблю тебя.',
        'Это действительно помогает мне.',
        'Она видит эту ошибку.',
        'Она мне помогает.',
        'Он чувствует себя счастливым.',
        'Это кажется интересным.',
        'Он хочет большего.',
        'Он также здесь работает.',
        'Они учатся очень усердно.',
        'Он действительно так думает.',
        'Мне это помогает.',
        'Это случается.',
        'Она живет в этом месте.',
        'Она хочет большего.',
        'Он хочет больше практики.',
        'Он живет там.',
        'Я чувствую себя счастливым.',
        'Мы хотим это.',
        'Она хочет больше практики.',
        'Она читает по-английски.',
        'Он любит тебя.',
        'Он знает больше.',
        'Я хочу больше практики.',
        'Он хочет сделать это.',
        'Она смотрит телевизор.',
        'У нее есть кошка.',
        'Она всегда делает это вовремя.',
        'Она ходит в школу.',
        'Он делает это каждый день.',
        'Он скучает по тебе.',
        'Она иногда ходит в кино.',
        'Он иногда играет в компьютерные игры.',
        'У него есть собака.',
        'Она преподает это.',
        'Он пытается найти работу.',
        'Он ходит на работу.',
    ];

    public function up()
    {
        $translations = [
            ['I remember it.'],
            ['I understand you.'],
            ['I think so.'],
            ['We speak English.'],
            ['I know it very well.'],
            ['You help me.'],
            ['I live in Russia.'],
            ['I understand you very well.'],
            ['I live in this city.'],
            ['We remember it.'],
            ['I speak English.'],
            ['I work there.'],
            ['They help me.'],
            ['We understand you.'],
            ['I have an idea.'],
            ['I have a brother.'],
            ['They go to school.'],
            ['You speak English very well.'],
            ['I have a car.'],
            ['We live here.'],
            ['I remember it very well.'],
            ['I go to work.'],
            ['I study here.'],
            ['I want it.'],
            ['We think so.'],
            ['I study there.'],
            ['I know it.'],
            ['I work here.'],
            ['They go to work.'],
            ['You know it.'],
            ['I work.'],
            ['I live in this country.'],
            ['We live in Russia.'],
            ['I have a sister.'],
            ['You see it.'],
            ['I go to school.'],
            ['I understand.'],
            ['We live in this country.'],
            ['I see it.'],
            ['It looks strange.'],
            ['He reads in English.'],
            ['She remembers it.'],
            ['It looks interesting.'],
            ['He works very hard.'],
            ['You work very hard.'],
            ['He helps me.'],
            ['He understands you very well.'],
            ['He also works here.'],
            ['It really happens.'],
            ['She works very hard.'],
            ['She feels happy.'],
            ['He also remembers it.'],
            ['He lives in this house.'],
            ['She also works there.'],
            ['He knows it.'],
            ['She really remembers it.'],
            ['She also thinks so.'],
            ['He also knows it.'],
            ['She lives in that place.'],
            ['She loves you.'],
            ['She speaks English very well.'],
            ['He thinks so.'],
            ['He lives in this country.'],
            ['She reads English books.'],
            ['I love you.'],
            ['It really helps me.'],
            ['She sees this mistake.'],
            ['She helps me.'],
            ['He feels happy.'],
            ['It seems interesting.'],
            ['He wants more.'],
            ['He also works here.'],
            ['They study very hard.'],
            ['He really thinks so.'],
            ['It helps me.'],
            ['It happens.'],
            ['She lives in this place.'],
            ['She wants more.'],
            ['He wants more practice.'],
            ['He lives there.'],
            ['I feel happy.'],
            ['We want it.'],
            ['She wants more practice.'],
            ['She reads in English.'],
            ['He loves you.'],
            ['He knows more.'],
            ['I want more practice.'],
            ['He wants to do it.'],
            ['She watches TV.'],
            ['She has a cat.'],
            ['She always does it on time.'],
            ['She goes to school.'],
            ['He does it every day.'],
            ['He misses you.'],
            ['She sometimes goes to the cinema.'],
            ['He sometimes plays computer games.'],
            ['He has a dog.'],
            ['She teaches it.'],
            ['He tries to find a job.'],
            ['He goes to work.'],
        ];

        foreach ($this->_sentences as $key => $sentence) {
            $model = Exercise::create(
                new ObjectId(),
                1,
                1,
                1,
                false,
                $sentence,
                $translations[$key],
                true
            );
            $model->save();
        }
    }

    public function down()
    {
        Exercise::deleteAll([
            'in',
            'sentence',
            $this->_sentences
        ]);
    }
}
