<?php

use app\models\grammar\exercise\Exercise;
use MongoDB\BSON\ObjectId;
use yii\mongodb\Migration;

class m200725_205251_fill_262_present_simple_exercise_collection extends Migration
{
    private array $_sentences = [
        'Я хочу говорить по-английски свободно и правильно.',
        'Я очень хочу это.',
        'Я хочу сделать это.',
        'Я хочу быть счастливым.',
        'Я хочу поблагодарить тебя.',
        'Я хочу лучше знать английский.',
        'Я очень хочу это знать.',
        'Я хочу новый компьютер.',
        'Я хочу лучше говорить по-английски.',
        'Я хочу говорить по-английски правильно.',
        'Мои родители хотят жить в другом месте.',
        'Я очень хочу улучшить свой английский.',
        'Я хочу пойти в другое место.',
        'Я хочу новую квартиру.',
        'Я хочу купить новую квартиру.',
        'Мой друг хочет жить за границей.',
        'Она хочет сделать это прямо сейчас.',
        'Мой друг хочет проверить это еще раз.',
        'Я очень хочу это.',
        'Я хочу поехать за границу.',
        'Я хочу эту вещь.',
        'Я хочу иметь хорошую машину.',
        'Я хочу быстро выучить английский.',
        'Мы хотим знать английский.',
        'Мне нравится это видео.',
        'Мне нравится эта вещь.',
        'Я хотел бы выпить чашечку кофе.',
        'Мне нравится этот плейлист.',
        'Я хотел бы сделать это.',
        'Я хотел бы посетить это место.',
        'Мне бы хотелось чашку кофе.',
        'Я хотел бы стать бизнесменом.',
        'Она хотела бы стать учителем.',
        'Ему нравится это платье.',
        'Я вижу тебе действительно нравится английский.',
        'Моему другу нравится этот отель.',
        'Мне нравится английский.',
        'Мне очень нравится этот плейлист.',
        'Мне нравится этот канал.',
        'Ей нравится это место.',
        'Тебе это нравится.',
        'Это ей нравится.',
        'Я вижу ему это очень нравится.',
        'Мне очень нравится этот канал.',
        'Я хотел бы знать английский очень хорошо.',
        'Им нравится это.',
        'Это мне нравится.',
        'Я хотел бы выпить чашечку чая.',
        'Мне нравится этот метод.',
        'Нам это нравится.',
        'Мне бы хотелось чашечку чая.',
        'Мне тоже нравится этот канал.',
        'Мне нравится этот канал тоже.',
        'Мне очень нравится это место.',
        'Мне это очень нравится.',
        'Он хотел бы стать врачом.',
        'Мне нравятся те уроки.',
        'Я хотел бы стать бизнесменом.',
        'Мне очень нравятся эти уроки.',
        'Я хотел бы стать менеджером.',
        'Мне нравится эта идея.',
        'Я хотел бы поехать за границу.',
        'Она хотела бы пойти в другое место.',
    ];

    public function up()
    {
        $translations = [
            ['I want to speak English fluently and correctly.'],
            ['I really want it.'],
            ['I want to do it.'],
            ['I want to be happy.'],
            ['I want to thank you.'],
            ['I want to know English better.'],
            ['I really want to know it.'],
            ['I want a new computer.'],
            ['I want to speak English better.'],
            ['I want to speak English correctly.'],
            ['My parents want to live in another place.'],
            ['I really want to improve my English.'],
            ['I want to go to another place.'],
            ['I want a new apartment.'],
            ['I want to buy a new apartment.'],
            ['My friends wants to live abroad.'],
            ['She wants to do it right now.'],
            ['My friend wants to check it one more time.'],
            ['I really want it.'],
            ['I want to go abroad.'],
            ['I want this thing.'],
            ['I want to have a good car.'],
            ['I want to learn English fast.'],
            ['We want to know English.'],
            ['I like this video.'],
            ['I like this thing.'],
            ['I`d like to drink a cup of coffee.'],
            ['I like this playlist.'],
            ['I`d like to do it.'],
            ['I`d like to visit this place.'],
            ['I`d like a cup of coffee.'],
            ['I`d like to become a businessman.'],
            ['She`d like to become a teacher.'],
            ['He likes this dress.'],
            ['I see you really like English.'],
            ['My friend likes this hotel.'],
            ['I like English.'],
            ['I really like this playlist.'],
            ['I like this channel.'],
            ['She likes this place.'],
            ['You like it.'],
            ['She likes it.'],
            ['I see he really likes it.'],
            ['I really like this channel.'],
            ['I`d like to know English very well.'],
            ['They like it.'],
            ['I like it.'],
            ['I`d like to drink a cup of tea.'],
            ['I like this method.'],
            ['We like it.'],
            ['I`d like a cup of tea.'],
            ['I also like this channel.'],
            ['I like this channel, too.'],
            ['I really like this place.'],
            ['I really like it.'],
            ['He`d like to become a doctor.'],
            ['I like those lessons.'],
            ['I`d like to become a businessman.'],
            ['I really like these lessons.'],
            ['I`d like to become a manager.'],
            ['I like this idea.'],
            ['I`d like to go abroad.'],
            ['She`d like to go to another place.'],
        ];

        foreach ($this->_sentences as $key => $sentence) {
            $model = Exercise::create(
                new ObjectId(),
                1,
                1,
                1,
                false,
                $sentence,
                $translations[$key],
                true
            );
            $model->save();
        }
    }

    public function down()
    {
        Exercise::deleteAll([
            'in',
            'sentence',
            $this->_sentences
        ]);
    }
}
