<?php

use app\models\grammar\exercise\Exercise;
use MongoDB\BSON\ObjectId;
use yii\mongodb\Migration;

class m200730_224357_fill_form_3_present_simple_exercise_collection extends Migration
{
    private array $_sentences = [
        'Ты все помнишь?',
        'Они поддерживают нас?',
        'Тебе нравится это?',
        'Ты хочешь учиться лучше?',
        'Ты часто пользуешься интернетом?',
        'Ты часто ходишь в спортзал?',
        'Ты поддерживаешь его?',
        'Ты ходишь в школу?',
        'У нас достаточно знаний?',
        'Ты хочешь знать свои ошибки?',
        'Мы показываем хорошие результаты?',
        'Тебе нужно решить эту проблему прямо сейчас?',
        'У тебя достаточно денег?',
        'У нас достаточно практики?',
        'Ты поддерживаешь его?',
        'Тебе нравится это платье?',
        'Они согласны с нами?',
        'Ты часто ходишь туда?',
        'Ты поддерживаешь меня?',
        'Вам нравится то предложение?',
        'Ты часто слушаешь музыку?',
        'Ты ходишь на работу?',
        'Ты согласен с ним?',
        'Ты пытаешься улучшить этот результат?',
        'У тебя есть свободное время?',
        'Ты меня понимаешь?',
        'Ты поддерживаешь это решение?',
        'Ты работаешь над своими ошибками?',
        'Тебе действительно нравится эта идея?',
        'Вам нужно больше денег?',
        'Ты согласен с ними?',
        'Я делаю ошибки?',
        'Ты помнишь это?',
        'Ты согласен с ней?',
        'Ты знаешь об этой проблеме?',
        'Ты часто делаешь это?',
        'Тебе нужна помощь?',
        'У меня достаточно денег?',
        'Ты согласен со мной?',
        'Ты часто посещаешь это место?',
        'Тебе нужен мой совет?',
        'Они поддерживают это решение?',
        'Они видят свои ошибки?',
        'Ты часто звонишь ему?',
        'Ему нравится это?',
        'Он ненавидит это?',
        'Он хочет жить за границей?',
        'Это кажется скучным?',
        'Она все говорит ему?',
        'Он там живет?',
        'Ей нужно прийти туда?',
        'Ей нужно прийти в то место?',
        'Ей действительно нравится это?',
        'Она часто слушает радио?',
        'Это кажется интересным?',
        'Он все игнорирует?',
        'Он пытается найти новую работу?',
        'Ему нравится этот проект?',
        'Ей нравится эта профессия?',
        'Он платит за это?',
        'Ей нужно позвонить ему?',
        'Она часто это говорит?',
        '?',
        '?',
        '?',
    ];// L15 7:17

    public function up()
    {
        $translations = [
            ['Do you remember everything?'],
            ['Do they support us?'],
            ['Do you like it?'],
            ['Do you want to study better?'],
            ['Do you often use the internet?'],
            ['Do you often go to the gym?'],
            ['Do you support him?'],
            ['Do you go to school?'],
            ['Do we have enough knowledge?'],
            ['Do you want to know your mistakes?'],
            ['Do we show good results?'],
            ['Do you need to solve this problem right now?'],
            ['Do you have enough money?'],
            ['Do we have enough practice?'],
            ['Do you support him?'],
            ['Do you like this dress?'],
            ['Do they agree with us?'],
            ['Do you often go there?'],
            ['Do you support me?'],
            ['Do you like that offer?'],
            ['Do you often listen to music?'],
            ['Do you go to work?'],
            ['Do you agree with him?'],
            ['Do you try to improve this result?'],
            ['Do you have free time?'],
            ['Do you understand me?'],
            ['Do you support this decision?'],
            ['Do you work on your mistakes?'],
            ['Do you really like this idea?'],
            ['Do you need more money?'],
            ['Do you agree with them?'],
            ['Do I make mistakes?'],
            ['Do you remember it?'],
            ['Do you agree with her?'],
            ['Do you know about this problem?'],
            ['Do you often do it?'],
            ['Do you need help?'],
            ['Do I have enough money?'],
            ['Do you agree with me?'],
            ['Do you often visit this place?'],
            ['Do you need my advice?'],
            ['Do they support this decision?'],
            ['Do they see their mistakes?'],
            ['Do you often call him?'],
            ['Does he like it?'],
            ['Does he hate it?'],
            ['Does he want to live abroad?'],
            ['Does it seem boring?'],
            ['Does she tell him everything?'],
            ['Does he live there?'],
            ['Does she need to come there?'],
            ['Does she need to come to that place?'],
            ['Does she really like it?'],
            ['Does she often listen to the radio?'],
            ['Does it seem interesting?'],
            ['Does he ignore everything?'],
            ['Does he try to find a new job?'],
            ['Does he like this project?'],
            ['Does she like this profession?'],
            ['Does he pay for it?'],
            ['Does she need to call him?'],
            ['Does she often say it?'],
            ['?'],
            ['?'],
            ['?'],
        ];

        foreach ($this->_sentences as $key => $sentence) {
            $model = Exercise::create(
                new ObjectId(),
                1,
                1,
                3,
                false,
                $sentence,
                $translations[$key],
                true
            );
            $model->save();
        }
    }

    public function down()
    {
        Exercise::deleteAll([
            'in',
            'sentence',
            $this->_sentences
        ]);
    }
}
