<?php

use app\models\grammar\exercise\Exercise;
use MongoDB\BSON\ObjectId;
use yii\mongodb\Migration;

class m200730_224357_fill_form_3_present_simple_exercise_collection extends Migration
{
    private array $_sentences = [
        'Ты все помнишь?',
        'Они поддерживают нас?',
        'Тебе нравится это?',
        'Ты хочешь учиться лучше?',
        'Ты часто пользуешься интернетом?',
        'Ты часто ходишь в спортзал?',
        'Ты поддерживаешь его?',
        'Ты ходишь в школу?',
        'У нас достаточно знаний?',
        'Ты хочешь знать свои ошибки?',
        'Мы показываем хорошие результаты?',
        'Тебе нужно решить эту проблему прямо сейчас?',
        'У тебя достаточно денег?',
        'У нас достаточно практики?',
        'Ты поддерживаешь его?',
        'Тебе нравится это платье?',
        'Они согласны с нами?',
        'Ты часто ходишь туда?',
        'Ты поддерживаешь меня?',
        'Вам нравится то предложение?',
        'Ты часто слушаешь музыку?',
        'Ты ходишь на работу?',
        'Ты согласен с ним?',
        'Ты пытаешься улучшить этот результат?',
        'У тебя есть свободное время?',
        'Ты меня понимаешь?',
        'Ты поддерживаешь это решение?',
        'Ты работаешь над своими ошибками?',
        'Тебе действительно нравится эта идея?',
        'Вам нужно больше денег?',
        'Ты согласен с ними?',
        'Я делаю ошибки?',
        'Ты помнишь это?',
        'Ты согласен с ней?',
        'Ты знаешь об этой проблеме?',
        'Ты часто делаешь это?',
        'Тебе нужна помощь?',
        'У меня достаточно денег?',
        'Ты согласен со мной?',
        'Ты часто посещаешь это место?',
        'Тебе нужен мой совет?',
        'Они поддерживают это решение?',
        'Они видят свои ошибки?',
        'Ты часто звонишь ему?',
        'Ему нравится это?',
        'Он ненавидит это?',
        'Он хочет жить за границей?',
        'Это кажется скучным?',
        'Она все говорит ему?',
        'Он там живет?',
        'Ей нужно прийти туда?',
        'Ей нужно прийти в то место?',
        'Ей действительно нравится это?',
        'Она часто слушает радио?',
        'Это кажется интересным?',
        'Он все игнорирует?',
        'Он пытается найти новую работу?',
        'Ему нравится этот проект?',
        'Ей нравится эта профессия?',
        'Он платит за это?',
        'Ей нужно позвонить ему?',
        'Она часто это говорит?',
        'Он часто говорит по-английски?',
        'Он часто говорит тебе эти вещи?',
        'Это иногда происходит?',
        'Она хочет поехать за границу?',
        'Она часто пользуется этим?',
        'Он ищет работу?',
        'Он ненавидит эту вещь?',
        'Он хочет работать в другом месте?',
        'Это действительно помогает тебе?',
        'Он игнорирует ее слова?',
        'Он помнит все эти правила?',
        'Это часто происходит?',
        'Он часто думает об этом?',
        'Он часто смотрит телевизор?',
        'Это выглядит странно?',
        'Он часто слышит это?',
        'Она преподает английский?',
        'Он всегда платит за нее?',
        'Она игнорирует это иногда?',
        'Эта вещь кажется важной?',
        'Твои родители понимают это?',
        'Этот экзамен кажется очень сложным?',
        'Этот студент показывает блестящие результаты?',
        'Твоя мать хочет сказать ему всю правду?',
        'Тот урок кажется скучным?',
        'Этот урок кажется полезным?',
        'Её парень хочет поехать за границу?',
        'Этот учитель объясняет все очень хорошо?',
        'Твоему отцу нужно это?',
        'Эти вещи кажутся неважными?',
        'Твой друг согласен с тобой?',
        'Твоему другу нравится эта идея?',
        'Эта информация кажется бесполезной?',
        'Этот канал помогает тебе?',
        'Тот тест кажется очень легким?',
        'Их начальник знает всю правду?',
        'Твой учитель видит это?',
        'Твои друзья согласны с тобой?',
        'Его девушка понимает это?',
        'Эти студенты показывают отличные результаты?',
        'Эта информация кажется неважной?',
        'Тот студент делает ошибки?',
        'Твои друзья всегда поддерживают тебя?',
        'Этот канал кажется очень интересным?',
        'Эти уроки помогают тебе?',
        'Этот результат мотивирует тебя?',
        'Эти результаты мотивируют тебя?',
        'Этот человек кажется очень хорошим?',
        'Те вещи интересуют его?',
        'Ей нравится эта идея?',
        'Деньги интересуют его?',
        'Эта женщина работает в другом месте?',
        'Она хочет решить эту проблему?',
        'Его слова мотивируют её?',
        'Твой отец приходит домой поздно?',
        'Этот отель выглядит очень хорошо?',
        'Ей нравится это место?',
        'Это кажется действительно интересным?',
        'Он пытается изменить это?',
        'Они согласны с этим?',
        'Кого ты знаешь?',
        'Когда ты ходишь на работу?',
        'Где они проводят время вместе?',
        'Почему ты согласен с ним?',
        'В какого рода компьютерные игры они играют?',
        'Во сколько ты ложишься спать?',
        'Что ты хочешь сказать?',
        'Что ты хочешь сделать?',
        'Как часто ты ходишь в спортзал?',
        'Сколько у тебя друзей?',
        'Как ты находишь эту идею?',
        'Кто это контролирует?',
        'Сколько ошибок ты обычно делаешь??',
        'Что тебе нужно сделать?',
        'Во сколько ты обычно встаешь?',
        'Что кажется странным?',
        'Почему ты так думаешь?',
        'Почему они зависят от тебя?',
        'Как ты проводишь свое свободное время?',
        'Когда у тебя есть свободное время?',
        'Что кажется важным?',
        'Что кажется неважным?',
        'Как часто ты пользуешься интернетом?',
        'Кто проверяет всю эту информацию?',
        'Как часто ты думаешь об этом?',
        'Что тебе помогает?',
        'Какого рода книги ты читаешь?',
        'Кто исправляет твои ошибки?',
        'Как часто ты смотришь телевизор?',
        'Как регулярно ты это проверяешь?',
        'Сколько английских слов ты знаешь?',
        'Что ты об этом думаешь?',
        'Кто тебя поддерживает?',
        'Какую музыку ты предпочитаешь?',
        'Где ты работаешь?',
        'Как регулярно ты занимаешься английским?',
        'Что ты знаешь?',
        'Кто это знает?',
        'Как ты добираешься домой?',
        'Как вы добираетесь до этого места?',
        'Что они хотят сказать тебе?',
        'Как часто ты слушаешь радио?',
        'Как ты обычно проводишь свое свободное время?',
        'Как ты обычно добираешься до того места?',
        'Куда ты ходишь?',
        'Что выглядит странно?',
        'Что кажется таким интересным?',
        'Почему тебе нравится этот канал?',
        'Кто все проверяет?',
        'Как ты добираешься туда?',
        'Где ты живешь?',
        'Кого ты поддерживаешь?',
        'Как часто ты ходишь туда?',
        'Почему ты хочешь посетить это место?',
        'Почему ты хочешь очень хорошо знать английский?',
        'Сколько у тебя с собой денег?',
        'Что кажется бесполезным?',
        'Когда ты чувствуешь себя счастливым?',
        'Что тебе здесь нравится?',
        'Что тебе реально помогает?',
        'Какие английские книги ты читаешь?',
        'Почему ты зависишь от него?',
        'Кто обычно это проверяет?',
        'Как ты добираешься до работы?',
        'Сколько у тебя свободного времени?',
        'Какие книги ты читаешь?',
        'Кто ходит на работу?',
        'Кто видит эти ошибки?',
        'Кого ты обычно там видишь?',
        'Что работает так хорошо?',
        'Сколько по времени занимает у тебя добраться до школы?',
        'Какие каналы он обычно смотрит?',
        'Какого рода фильмы она смотрит?',
        'Как он добирается домой?',
        'Почему это привлекает тебя?',
        'Что ему нужно изменить?',
        'Какие напитки она предпочитает?',
        'Почему он отказывается это делать?',
        'Сколько по времени занимает у тебя добраться до работы?',
        'Почему это выглядит странно?',
        'Как регулярно он делает эти упражнения?',
        'Что она хочет добавить?',
        'Сколько английских слов он знает?',
        'Когда это происходит?',
        'Что тебя интересует?',
        'Что он помнит?',
        'Что тебе помогает?',
        'Как это помогает тебе?',
        'В какое время он приходит на работу?',
        'Кто мотивирует тебя?',
        'Что она пытается сделать?',
        'Когда он чувствует себя счастливым?',
        'Во сколько она уходит из дома?',
        'Почему это кажется бесполезным?',
        'Какие у него английские книги?',
        'Какие книги она предпочитает читать?',
        'Что тебя беспокоит?',
        'Кто хочет жить за границей?',
        'Что привлекает его там?',
        'Как он тебя поддерживает?',
        'Что тебя больше беспокоит?',
        'Почему он всегда жалуется на это?',
        'Что мотивирует тебя больше?',
        'Что он хочет добавить?',
        'Который канал он обычно смотрит?',
        'Где она учится?',
        'Какой напиток она предпочитает: чай или кофе?',
        'Кто тебя поддерживает?',
        'Как часто она ходит в кино?',
        'Как она собирается домой?',
        'Она смотрит разные фильмы?',
        'Кого он поддерживает?',
        'Почему это происходит снова и снова?',
        'Куда она обычно ходит?',
        'Какой совет она тебе дает?',
        'Как часто он ходит в зоопарк?',
        'Что тебе действительно помогает?',
        'Кого это волнует?',
        'Сколько по времени занимает у неё добраться до этого места?',
        'Как она это объясняет?',
        'Кто любит её?',
        'Сколько по времени занимает у него добраться до того места?',
        'Почему он так часто жалуется?',
        'Почему это его интересует?',
        'Как она тренирует свою память?',
        'Почему она отказывается платить?',
        'Как он обычно проводит свое свободное время?',
        'Где он работает?',
        'Сколько у него долларов?',
        'Какие каналы он смотрит?',
        'Кого это мотивирует?',
        'Как он решает эти проблемы?',
        'Что она хочет добавить?',
        'Кого она любит?',
        'Сколько денег она платит?',
        'Что она обычно говорит?',
        'Как твой брат контролирует это?',
        'Почему твои друзья не согласны с тобой?',
        'Как чувствует твоя сестра?',
        'Как регулярно ваш начальник проверяет это?',
        'Сколько английских слов хочет знать твой друг?',
        'Какой совет тебе дают твои друзья?',
        'Почему ваш начальник критикует это?',
        'Почему твои родители не согласны с тобой?',
        'Какой совет дает тебе твой учитель?',
        'Что обычно заказывают твои друзья?',
        'Почему твой друг хочет искать новую работу?',
        'Где работает твой отец?',
        'Сколько времени занимает у его дочери добраться до школы?',
        'Почему твоя мама так думает?',
        'Какой совет дают тебе твои учителя?',
        'Сколько свободного времени у твоего делового партнера?',
        'Сколько по времени занимает у его сына добраться до работы?',
        'Какого рода примеры даёт его учитель?',
        'Где живут твои родители?',
        'Когда твой отец уходит из дома?',
        'Во сколько твоя мама приходит на работу?',
        'Как часто происходят эти вещи?',
        'Когда происходят те вещи?',
        'Сколько по времени занимает у твоего друга добраться туда?',
        'Что обычно обещает твой начальник?',
        'Почему эта идея кажется такой интересной?',
        'Как регулярно твой учитель говорит это?',
        'Что кажется неважным?',
        'Почему она отказывается платить?',
        'Где работает твой отец?',
        '?',
        '?',
        '?',
        '?',
    ];// L23 1:17

    public function up()
    {
        $translations = [
            ['Do you remember everything?'],
            ['Do they support us?'],
            ['Do you like it?'],
            ['Do you want to study better?'],
            ['Do you often use the internet?'],
            ['Do you often go to the gym?'],
            ['Do you support him?'],
            ['Do you go to school?'],
            ['Do we have enough knowledge?'],
            ['Do you want to know your mistakes?'],
            ['Do we show good results?'],
            ['Do you need to solve this problem right now?'],
            ['Do you have enough money?'],
            ['Do we have enough practice?'],
            ['Do you support him?'],
            ['Do you like this dress?'],
            ['Do they agree with us?'],
            ['Do you often go there?'],
            ['Do you support me?'],
            ['Do you like that offer?'],
            ['Do you often listen to music?'],
            ['Do you go to work?'],
            ['Do you agree with him?'],
            ['Do you try to improve this result?'],
            ['Do you have free time?'],
            ['Do you understand me?'],
            ['Do you support this decision?'],
            ['Do you work on your mistakes?'],
            ['Do you really like this idea?'],
            ['Do you need more money?'],
            ['Do you agree with them?'],
            ['Do I make mistakes?'],
            ['Do you remember it?'],
            ['Do you agree with her?'],
            ['Do you know about this problem?'],
            ['Do you often do it?'],
            ['Do you need help?'],
            ['Do I have enough money?'],
            ['Do you agree with me?'],
            ['Do you often visit this place?'],
            ['Do you need my advice?'],
            ['Do they support this decision?'],
            ['Do they see their mistakes?'],
            ['Do you often call him?'],
            ['Does he like it?'],
            ['Does he hate it?'],
            ['Does he want to live abroad?'],
            ['Does it seem boring?'],
            ['Does she tell him everything?'],
            ['Does he live there?'],
            ['Does she need to come there?'],
            ['Does she need to come to that place?'],
            ['Does she really like it?'],
            ['Does she often listen to the radio?'],
            ['Does it seem interesting?'],
            ['Does he ignore everything?'],
            ['Does he try to find a new job?'],
            ['Does he like this project?'],
            ['Does she like this profession?'],
            ['Does he pay for it?'],
            ['Does she need to call him?'],
            ['Does she often say it?'],
            ['Does he often speak English?'],
            ['Does he often tell you these things?'],
            ['Does it sometimes happen?'],
            ['Does she want to go abroad?'],
            ['Does she often use it?'],
            ['Does he look for a job?'],
            ['Does he hate this thing?'],
            ['Does he want to work in another place?'],
            ['Does it really help you?'],
            ['Does he ignore her words?'],
            ['Does he remember all these rules?'],
            ['Does it often happen?'],
            ['Does he often think about it?'],
            ['Does he often watch TV?'],
            ['Does it look strange?'],
            ['Does he often hear it?'],
            ['Does she teach English?'],
            ['Does he always pay for her?'],
            ['Does she ignore it sometimes?'],
            ['Does this thing seem important?'],
            ['Do your parents understand it?'],
            ['Does this exam seem very difficult?'],
            ['Does this student show brilliant results?'],
            ['Does your mother want to tell him all the truth?'],
            ['Does that lesson seem boring?'],
            ['Does this lesson seem useful?'],
            ['Does her boyfriend want to go abroad?'],
            ['Does this teacher explain everything very well?'],
            ['Does your father need it?'],
            ['Do these things seem unimportant?'],
            ['Does your friend agree with you?'],
            ['Does your friend like this idea?'],
            ['Does this information seem useless?'],
            ['Does this channel help you?'],
            ['Does that test seem very easy?'],
            ['Does their boss know all the truth?'],
            ['Does your teacher see it?'],
            ['Do your friends agree with you?'],
            ['Does his girlfriend understand it?'],
            ['Do these students show excellent results?'],
            ['Does this information seem unimportant?'],
            ['Does that student make mistakes?'],
            ['Do your friends always support you?'],
            ['Does this channel seem very interesting?'],
            ['Do these lessons helps you?'],
            ['Does this result motivate you?'],
            ['Do these results motivate you?'],
            ['Does this person seem very good?'],
            ['Do those things interest him?'],
            ['Does she like this idea?'],
            ['Does money interest him?'],
            ['Does this woman work in another place?'],
            ['Does she want to solve this problem?'],
            ['Do his words motivate her?'],
            ['Does your father come home late?'],
            ['Does this hotel look very good?'],
            ['Does she like this place?'],
            ['Does it seem really interesting?'],
            ['Does he try to change it?'],
            ['Do they agree with it?'],
            ['Who do you know?'],
            ['When do you go to work?'],
            ['Where do they spend time together?'],
            ['Why do you agree with him?'],
            ['What kind of computer games do they play?'],
            ['What time do you go to bed?'],
            ['What do you want to say?'],
            ['What do you want to do?'],
            ['How often do you go to the gym?'],
            ['How many friends do you have?'],
            ['How do you find this idea?'],
            ['Who controls it?'],
            ['How many mistakes do you usually make?'],
            ['What do you need to do?'],
            ['What time do you usually get up?'],
            ['What seems strange?'],
            ['Why do you think so?'],
            ['Why do they depend on you?'],
            ['How do you spend your free time?'],
            ['When do you have free time?'],
            ['What seems important?'],
            ['What seems unimportant?'],
            ['How often do you use the Internet?'],
            ['Who checks all this information?'],
            ['How often do you think about it?'],
            ['What helps you?'],
            ['What kind of books do you read?'],
            ['Who corrects your mistakes?', 'Who fixes your mistakes?'],
            ['How often do you watch TV?'],
            ['How regularly do you check it?'],
            ['How many English words do you know?'],
            ['What do you think about it?'],
            ['Who supports you?'],
            ['What music do you prefer?'],
            ['Where do you work?'],
            ['How regularly do you learn English?'],
            ['What do you know?'],
            ['Who knows it?'],
            ['How do you get home?'],
            ['How do you get to this place?'],
            ['What do they want to tell you?'],
            ['How often do you listen to the radio?'],
            ['How do you usually spend your free time?'],
            ['How do you usually get to that place?'],
            ['Where do you go?'],
            ['What looks strange?'],
            ['What seems so interesting?'],
            ['Why do you like this channel?'],
            ['Who checks everything?'],
            ['How do you get there?'],
            ['Where do you live?'],
            ['Who do you support?'],
            ['How often do you go there?'],
            ['Why do you want to visit this place?'],
            ['Why do you want to know English very well?'],
            ['How much money do you have with you?'],
            ['What seems useless?'],
            ['How do you feel happy?'],
            ['What do you like here?'],
            ['What really helps you?'],
            ['What English books do you read?'],
            ['Why do you depend on him?'],
            ['Who usually checks it?'],
            ['How do you get to work?'],
            ['How much free time do you have?'],
            ['What books do you read?'],
            ['Who goes to work?'],
            ['Who sees these mistakes?'],
            ['Who do you usually see there?'],
            ['What works so well?'],
            ['How long does it take you to get to school?'],
            ['What channels does he usually watch?'],
            ['What kind of movies does she watch?', 'What kind of films does she watch?'],
            ['How does he get home?'],
            ['Why does it attract you?'],
            ['What does he need to change?'],
            ['What drinks does she prefer?'],
            ['Why does he refuse to do it?'],
            ['How long does it take you to get to work?'],
            ['Why does it look strange?'],
            ['How regularly does he do these exercises?'],
            ['What does she want to add?'],
            ['How many English words does he know?'],
            ['When does it happen?'],
            ['What interests you?'],
            ['What does he remember?'],
            ['What helps you?'],
            ['How does it help you?'],
            ['What time does he come to work?'],
            ['Who motivates you?'],
            ['What does she try to do?'],
            ['When does he feel happy?'],
            ['What time does she leave home?'],
            ['Why does it seem useless?'],
            ['What English books does he have ?'],
            ['What books does she prefer to read?'],
            ['What worries you?'],
            ['Who wants to live abroad?'],
            ['What attracts him there?'],
            ['How does he support you?'],
            ['What worries you more?'],
            ['Why does he always complain about it?'],
            ['What motivates you more?'],
            ['What does he want to add?'],
            ['Which channel does he usually watch?'],
            ['Where does she study?'],
            ['What drink does she prefer: tea or coffee?'],
            ['Who supports you?'],
            ['How often does she go to the cinema?'],
            ['How does she get home?'],
            ['She watches different movies?'],
            ['Who does he support?'],
            ['Why does it happen again and again?'],
            ['Where does she usually go?'],
            ['What advice does she give you?'],
            ['How often does he go to the zoo?'],
            ['What really helps you?'],
            ['Who does it worry?'],
            ['How long does it take her to get to this place?'],
            ['How does she explain it?'],
            ['Who loves her?'],
            ['How long does it take him to get to that place?'],
            ['Why does he complain so often?'],
            ['Why does it interest him?'],
            ['How does she train her memory?'],
            ['Why does she refuse to pay?'],
            ['How does he usually spend his free time?'],
            ['Where does he work?'],
            ['How many dollars does he have?'],
            ['Which channels does he watch?'],
            ['Who does it motivate?'],
            ['How does he solve these problems?'],
            ['What does she want to add?'],
            ['Who does she love?'],
            ['How much money does she pay?'],
            ['What does she usually say?'],
            ['How does your brother control it?'],
            ['Why do your friends disagree with you?'],
            ['How does your sister feel?'],
            ['How regularly does your boss check it?'],
            ['How many English words does your friend want to know?'],
            ['What advice do your friends give you?'],
            ['Why does your boss criticize it?'],
            ['Why do your parents disagree with you?'],
            ['What advice does your teacher give you?'],
            ['What do your friends usually order?'],
            ['Why does your friend want to look for a new job?'],
            ['Where does your father work?'],
            ['How long does it take his daughter to get to school?'],
            ['Why does your mom think so?', 'Why does your mother think so?'],
            ['What advice do your teachers give you?'],
            ['How much free time does your business partner have?'],
            ['How long does it take his son to get to work?'],
            ['What kind of examples does his teacher give?'],
            ['Where do your parents live?'],
            ['When does your father leave home?'],
            ['What time does your mom come to work?', 'What time does your mother come to work?'],
            ['How often do these things happen?'],
            ['When do those things happen?'],
            ['How long does it take your friend to get there?'],
            ['What does your boss usually promise?'],
            ['Why does this idea seem so interesting?'],
            ['How regularly does your teacher say it?'],
            ['What seems unimportant?'],
            ['Why does she refuse to pay?'],
            ['Where does your father work?'],
            ['?'],
            ['?'],
            ['?'],
            ['?'],
        ];

        foreach ($this->_sentences as $key => $sentence) {
            $model = Exercise::create(
                new ObjectId(),
                1,
                1,
                3,
                false,
                $sentence,
                $translations[$key],
                true
            );
            $model->save();
        }
    }

    public function down()
    {
        Exercise::deleteAll([
            'in',
            'sentence',
            $this->_sentences
        ]);
    }
}
